# docker compose up --build --force-recreate

version: "3"

services:
  app:
    image: docker-nextjs-dev
    container_name: app
    build: .
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./:/app/

  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
