# docker compose up --build --force-recreate

version: "3"

services:
  app:
    image: docker-nextjs-dev
    build: .
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./:/app/
