version: "3"

services:
  app:
    image: docker-nextjs:dev
    container_name: app
    build: .
    depends_on:
      - db
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: >
      /bin/bash -c "yarn install && yarn dev"

  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
