version: "3"

services:
  app:
    image: docker-nextjs:production
    container_name: app
    depends_on:
      - db
    build:
      dockerfile: Dockerfile.production
    environment:
      - PORT=3000
    ports:
      - 3000:3000

  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata_production:/var/lib/postgresql/data

volumes:
  pgdata_production:
